name: Update survey from Excel

on:
  workflow_dispatch:   # 只保留手动触发

permissions:
  contents: write      # 允许工作流向仓库推送 commit

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check secret exists
        run: |
          if [ -z "${OD_PUBLIC_URL}" ]; then
            echo "OD_PUBLIC_URL is empty! Please set repository secret."
            exit 1
          fi
        env:
          OD_PUBLIC_URL: ${{ secrets.OD_PUBLIC_URL }}

      - name: Download survey.json from OneDrive/SharePoint
        run: |
          curl -L "$OD_PUBLIC_URL" -o survey.json
          echo "Downloaded size:"
          ls -l survey.json
        env:
          OD_PUBLIC_URL: ${{ secrets.OD_PUBLIC_URL }}

      - name: Commit & push if changed
        run: |
          if git diff --quiet --exit-code survey.json; then
            echo "No change in survey.json."
          else
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add survey.json
            git commit -m "chore: update survey.json from OneDrive $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
